# Generated by Django 4.2.14 on 2025-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
